name: "File existence check"
on:
  push:
    branches: [ Development ]
  pull_request:
    branches: [ Development ]

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
         with:
            server_address: smtp.gmail.com
            # Required mail server port:
            server_port: 465
            # Optional (recommended): mail server username:
            username: ${{secrets.MAIL_USERNAME}}
            # Optional (recommended) mail server password:
            password: ${{secrets.MAIL_PASSWORD}}
            # Required mail subject:
            subject: Github Actions job result
            # Required recipients' addresses:
            to: obiwan@example.com,yoda@example.com
            # Required sender full name (address can be skipped):
            from: Luke Skywalker # <user@example.com>
            # Optional whether this connection use TLS (default is true if server_port is 465)
            secure: true
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "Dockerfile,docker-compose.yml,container_name.txt"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        # Only runs if all of the files exists
        run: echo All files exists!
