name: "File existence check"
on:
  push:
    branches: [ Development ]
jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "Dockerfile,docker-compose.yml,container.txt"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        # Only runs if all of the files exists
        run: exit 1
        
        
