name: Build

on:
  push:
    branches: Staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hello World
        run: echo Hello, world && exit 0
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
         # mail server settings
         server_address: smtp.gmail.com
         server_port: 465
         # user credentials
         username: ${{ secrets.MAIL_USERNAME }}
         password: ${{ secrets.MAIL_PASSWORD }}
         # email subject
         subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
         # email body as text
         body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
         # comma-separated string, send email to
         to: mirzamohammadhamza@outlook.com
         # from email name
         from: Mirza Mohammad Hamza
