name: Manual_Trigger

on:
    workflow_dispatch:
       inputs:
         loglevel:
            description: 'LOG Level'
            required: true
            default: 'warning'
         tags:
             description: 'Test Sanarios Tags'
             required: true
             default: 'Tags'
             
jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
          DAY_OF_WEEK: Monday
          Greeting: Hello
